class UserAlreadyExistsError(Exception):
    """Raised when attempting to create an account that already exists."""
    pass
